name: Build Super3 APK (Release)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK and CMake
      run: |
        sdkmanager "ndk;25.2.9519653" "cmake;3.30.3"

    - name: Patch and Build
      run: |
        # 1. Fix the -Xmx64m memory bug in all gradlew files
        find . -name "gradlew" -exec sed -i 's/DEFAULT_JVM_OPTS=.*/DEFAULT_JVM_OPTS=""/g' {} +
        find . -name "gradlew" -exec sed -i 's/\r$//' {} +

        # 2. Force Java 17 and Kotlin compatibility across the project
        find . -name "build.gradle*" -exec sed -i 's/JavaVersion.VERSION_[0-9_]*/JavaVersion.VERSION_17/g' {} +
        find . -name "build.gradle*" -exec sed -i "s/jvmTarget = .*/jvmTarget = '17'/g" {} +

        # 3. FIX: Add signing config using Kotlin DSL syntax for .kts files
        find . -name "build.gradle.kts" -exec sed -i '/release {/a \            signingConfig = signingConfigs.getByName("debug")' {} +
        
        # 4. Add signing config using Groovy syntax for any standard .gradle files
        find . -name "build.gradle" ! -name "*.kts" -exec sed -i '/release {/a \            signingConfig signingConfigs.debug' {} +

        # 5. Clear Java environment variables to prevent startup crashes
        unset _JAVA_OPTIONS
        unset JAVA_TOOL_OPTIONS
        unset JAVA_OPTS

        # 6. Build the optimized Release version
        cd android
        chmod +x gradlew
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653
        
        ./gradlew assembleRelease \
          -Dorg.gradle.java.home=$JAVA_HOME_17_X64 \
          -Dorg.gradle.jvmargs="-Xmx2048m" \
          -Pandroid.kotlinOptions.jvmTarget=17

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Super3-Odin-Release
        path: android/app/build/outputs/apk/release/*.apk
